alias vim="nvim"
alias pbcopy="xsel -ib"
alias pbpaste="xsel -b"
alias ws="cd ~/workspace"
alias ops="cd ~/workspace/devops"
alias tmux="tmux a || tmux"
alias karousel="cd ~/workspace/go/src/github.com/mavenlink/karousel"
