#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# A command to launch a new, anonymous Chrome session for testing.
chrome() {
  mkdir -p /tmp/chrome$1
  ~/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/chrome$1
}

# Load fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


unsetopt AUTO_NAME_DIRS

# Source aliases
source ~/.aliases.sh

source <(kubectl completion zsh)
export GOPATH=~/workspace/go
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
export PATH=$PATH:/opt/goland/bin
export PATH=$PATH:$HOME/workspace/blackbox/bin


# (wal -r &)

cpstat () {
  tar cf - "$1" | pv | (cd "$2";tar xf -)
}

eval "$(rbenv init -)"

