#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# SSH agent
# if [[ -z "$SSH_AUTH_SOCK" ]]; then
#   export SSH_AUTH_SOCK=$(ls ~/.ssh/agent/s.* 2>/dev/null | head -1)
# fi
